export const FETCH_PO_CATEGORY = 'FETCH_PO_CATEGORY';
export const PO_SEARCH_RESULT_SUCCESS = 'PO_SEARCH_RESULT_SUCCESS';
export const PO_SEARCH_FAILURE = 'PO_SEARCH_FAILURE';
export const LOADING = 'LOADING';
export const PO_FILTER_RESULTS = 'PO_FILTER_RESULTS';
export const OPEN_HAMBURGER = 'OPEN_HAMBURGER';
export const CLOSE_HAMBURGER = 'CLOSE_HAMBURGER';
export const FETCH_MENU_LIST = 'FETCH_MENU_LIST';
